---

- name: install curl
  become: true
  package:
    name: curl
    state: latest

- name: install vim
  become: true
  package:
    name: vim
    state: latest

- name: install dos2unix
  become: true
  package:
    name: dos2unix
    state: latest

- name: install tree
  become: true
  package:
    name: tree
    state: latest

- name: install jq
  become: true
  package:
    name: jq
    state: latest
